import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  fullScreenButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  inGameScore: {
    fontSize: 120,
    fontWeight: '900',
    color: 'rgba(255,255,255,0.6)',
    textShadowColor: 'rgba(0, 0, 0, 0.4)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
    position: 'absolute',
    top: 80,
  },
  playArea: {
    width: 300,
    height: 300,
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: 80,
  },
  dirtBase: {
    position: 'absolute',
    bottom: 25,
    width: 280,
    height: 120,
    backgroundColor: '#4E342E',
    borderRadius: 140,
    borderBottomWidth: 12,
    borderBottomColor: '#3E2723',
  },
  holeRim: {
    position: 'absolute',
    bottom: 60,
    width: 180,
    height: 60,
    backgroundColor: '#3E2723',
    borderRadius: 90,
  },
  holeOpening: {
    position: 'absolute',
    bottom: 63,
    width: 170,
    height: 54,
    backgroundColor: '#110804',
    borderRadius: 85,
  },
  svgContainer: {
    position: 'absolute',
    bottom: -10,
    width: 200,
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{ scaleY: 0.333 }],
    zIndex: 5,
  },
  maskContainer: {
    position: 'absolute',
    bottom: 90,
    width: 170,
    height: 160,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  holeFrontLip: {
    position: 'absolute',
    bottom: 60,
    width: 180,
    height: 30,
    backgroundColor: 'transparent',
  },
  plusOneText: {
    position: 'absolute',
    bottom: 180,
    fontSize: 48,
    fontWeight: '900',
    color: '#FFD700',
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
    zIndex: 10,
  },
  entityContainer: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    height: 130,
    paddingBottom: 5,
  },
  moleBody: {
    width: 90,
    height: 110,
    backgroundColor: '#8B5A2B',
    borderTopLeftRadius: 45,
    borderTopRightRadius: 45,
    alignItems: 'center',
    paddingTop: 20,
  },
  moleEyesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 50,
    marginBottom: 10,
  },
  moleEye: {
    width: 12,
    height: 12,
    backgroundColor: '#000',
    borderRadius: 6,
  },
  moleNose: {
    width: 24,
    height: 16,
    backgroundColor: '#FFB6C1',
    borderRadius: 8,
    marginBottom: 10,
  },
  moleMouth: {
    width: 20,
    height: 10,
    backgroundColor: '#3E2723',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    alignItems: 'center',
  },
  moleTooth: {
    width: 8,
    height: 6,
    backgroundColor: '#FFF',
  },
  bombContainer: {
    alignItems: 'center',
    width: 90,
    height: 110,
    justifyContent: 'flex-end',
    paddingBottom: 10,
  },
  bombSpark: {
    width: 16,
    height: 16,
    backgroundColor: '#FF4500',
    borderRadius: 8,
    marginBottom: -5,
    zIndex: 2,
  },
  bombCap: {
    width: 24,
    height: 12,
    backgroundColor: '#777',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  bombBody: {
    width: 80,
    height: 80,
    backgroundColor: '#222',
    borderRadius: 40,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    paddingTop: 15,
    paddingLeft: 15,
  },
  bombHighlight: {
    width: 20,
    height: 20,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 10,
  },
});