import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  fullScreenButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  inGameScore: {
    fontSize: 80,
    fontWeight: '900',
    color: 'rgba(255,255,255,0.6)',
    textShadowColor: 'rgba(0, 0, 0, 0.4)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
    position: 'absolute',
    top: 60,
  },
  gridArea: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: 340,
    justifyContent: 'center',
    marginTop: 100,
  },
  holeWrapper: {
    width: 100,
    height: 110,
    alignItems: 'center',
    justifyContent: 'flex-end',
    margin: 5,
  },
  dirtBase: {
    position: 'absolute',
    bottom: 10,
    width: 90,
    height: 40,
    backgroundColor: '#4E342E',
    borderRadius: 45,
    borderBottomWidth: 6,
    borderBottomColor: '#3E2723',
  },
  holeRim: {
    position: 'absolute',
    bottom: 25,
    width: 70,
    height: 25,
    backgroundColor: '#3E2723',
    borderRadius: 35,
  },
  holeOpening: {
    position: 'absolute',
    bottom: 27,
    width: 66,
    height: 20,
    backgroundColor: '#110804',
    borderRadius: 33,
  },
  maskContainer: {
    position: 'absolute',
    bottom: 35,
    width: 70,
    height: 75,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  holeFrontLip: {
    position: 'absolute',
    bottom: 25,
    width: 70,
    height: 12,
    backgroundColor: 'transparent',
  },
  plusOneText: {
    position: 'absolute',
    bottom: 80,
    fontSize: 24,
    fontWeight: '900',
    color: '#FFD700',
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    zIndex: 10,
  },
  entityContainer: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    height: 70,
    paddingBottom: 2,
  },
  moleBody: {
    width: 50,
    height: 65,
    backgroundColor: '#8B5A2B',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    alignItems: 'center',
    paddingTop: 12,
  },
  moleEyesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 28,
    marginBottom: 6,
  },
  moleEye: {
    width: 6,
    height: 6,
    backgroundColor: '#000',
    borderRadius: 3,
  },
  moleNose: {
    width: 14,
    height: 8,
    backgroundColor: '#FFB6C1',
    borderRadius: 4,
    marginBottom: 6,
  },
  moleMouth: {
    width: 12,
    height: 6,
    backgroundColor: '#3E2723',
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
    alignItems: 'center',
  },
  moleTooth: {
    width: 4,
    height: 4,
    backgroundColor: '#FFF',
  },
  bombContainer: {
    alignItems: 'center',
    width: 50,
    height: 65,
    justifyContent: 'flex-end',
    paddingBottom: 5,
  },
  bombSpark: {
    width: 10,
    height: 10,
    backgroundColor: '#FF4500',
    borderRadius: 5,
    marginBottom: -2,
    zIndex: 2,
  },
  bombCap: {
    width: 14,
    height: 6,
    backgroundColor: '#777',
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
  },
  bombBody: {
    width: 45,
    height: 45,
    backgroundColor: '#222',
    borderRadius: 22.5,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    paddingTop: 8,
    paddingLeft: 8,
  },
  bombHighlight: {
    width: 12,
    height: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 6,
  },
});