import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  fullScreenButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  musicToggle: {
    position: 'absolute',
    top: 50,
    right: 20,
    backgroundColor: '#8D6E63',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 25,
    borderWidth: 3,
    borderColor: '#4E342E',
    zIndex: 100,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 6,
  },
  musicToggleText: {
    fontSize: 16,
    fontWeight: '900',
    color: '#FFF8DC',
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    height: 180,
    width: 180,
    marginBottom: 20,
    zIndex: 2,
  },
  dirtMound: {
    width: 120,
    height: 48,
    backgroundColor: '#4E342E',
    borderRadius: 60,
    borderBottomWidth: 10,
    borderBottomColor: '#3E2723',
    position: 'absolute',
    bottom: 10,
  },
  sprout: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 20,
    borderRightWidth: 20,
    borderBottomWidth: 50,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#689F38',
    position: 'absolute',
    bottom: 30,
    borderRadius: 5,
  },
  loadingText: {
    marginTop: 20,
    fontSize: 26,
    fontWeight: '900',
    color: '#FFF8DC',
    letterSpacing: 3,
    textShadowColor: '#3E2723',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 1,
  },
  gameOverTitle: {
    fontSize: 56,
    fontWeight: '900',
    color: '#FFF8DC',
    textShadowColor: '#3E2723',
    textShadowOffset: { width: 3, height: 4 },
    textShadowRadius: 2,
    marginBottom: 40,
    letterSpacing: 2,
  },
  finalScoreBoard: {
    backgroundColor: '#5D4037',
    paddingVertical: 20,
    paddingHorizontal: 40,
    borderRadius: 12,
    borderWidth: 5,
    borderColor: '#3E2723',
    alignItems: 'center',
    marginBottom: 20,
    width: 260,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.7,
    shadowRadius: 6,
    elevation: 10,
  },
  finalScoreLabel: {
    fontSize: 20,
    color: '#D7CCC8',
    fontWeight: '900',
    letterSpacing: 3,
    marginBottom: 5,
    textShadowColor: '#3E2723',
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 1,
  },
  finalScoreNumber: {
    fontSize: 68,
    color: '#FFFFFF',
    fontWeight: '900',
    textShadowColor: '#271815',
    textShadowOffset: { width: 2, height: 4 },
    textShadowRadius: 2,
  },
  highScoreBoard: {
    backgroundColor: '#8D6E63',
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 12,
    borderWidth: 4,
    borderColor: '#4E342E',
    alignItems: 'center',
    marginBottom: 40,
    width: 260,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.6,
    shadowRadius: 5,
    elevation: 8,
  },
  highScoreLabel: {
    fontSize: 18,
    color: '#EFEBE9',
    fontWeight: '900',
    letterSpacing: 2,
    marginBottom: 5,
    textShadowColor: '#4E342E',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
  highScoreNumber: {
    fontSize: 48,
    color: '#FFD700',
    fontWeight: '900',
    textShadowColor: '#4E342E',
    textShadowOffset: { width: 2, height: 3 },
    textShadowRadius: 1,
  },
  subtitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFF8DC',
    marginTop: 20,
    textShadowColor: '#3E2723',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 2,
  },
  gameOverReasonText: {
    fontSize: 24,
    fontWeight: '900',
    color: '#FF6347',
    marginBottom: 30,
    textShadowColor: '#3E2723',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 1,
    textAlign: 'center',
    letterSpacing: 1,
  },
});