import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  fullScreenButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  splashLogoContainer: {
    width: 150,
    height: 150,
    backgroundColor: '#3E2723',
    borderRadius: 75,
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginBottom: 50,
    borderWidth: 8,
    borderColor: '#5C4033',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.6,
    shadowRadius: 5,
    elevation: 10,
  },
  title: {
    fontSize: 38,
    fontWeight: '900',
    color: '#FFF8DC',
    textShadowColor: '#3E2723',
    textShadowOffset: { width: 3, height: 4 },
    textShadowRadius: 2,
    marginBottom: 30,
    textAlign: 'center',
    letterSpacing: 1,
  },
  scoreBoard: {
    backgroundColor: '#A0522D',
    paddingHorizontal: 40,
    paddingVertical: 15,
    borderRadius: 15,
    marginBottom: 40,
    alignItems: 'center',
    borderWidth: 6,
    borderColor: '#5C4033',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.6,
    shadowRadius: 5,
    elevation: 8,
  },
  scoreText: {
    fontSize: 26,
    fontWeight: '900',
    color: '#FFF8DC',
    textShadowColor: '#3E2723',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 1,
  },
  subtitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFF8DC',
    marginBottom: 10,
    textShadowColor: '#3E2723',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 2,
  },
  moleBody: {
    width: 100,
    height: 120,
    backgroundColor: '#8B5A2B',
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    alignItems: 'center',
    paddingTop: 25,
  },
  moleEyesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 55,
    marginBottom: 12,
  },
  moleEye: {
    width: 14,
    height: 14,
    backgroundColor: '#000',
    borderRadius: 7,
  },
  moleNose: {
    width: 28,
    height: 18,
    backgroundColor: '#FFB6C1',
    borderRadius: 9,
    marginBottom: 12,
  },
  moleMouth: {
    width: 24,
    height: 12,
    backgroundColor: '#3E2723',
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    alignItems: 'center',
  },
  moleTooth: {
    width: 10,
    height: 8,
    backgroundColor: '#FFF',
  },
});